version: '3.8'
services:
  # Creates the cassandra node
  cassandra:
    image: cassandra
    container_name: cassandra
    build:
      context: .
      dockerfile: Dockerfile.cassandra
      args:
        CONFIG_PATH: ${CONFIG_PATH}
        CQL_PATH: ${CQL_PATH}
    ports:
      - "9042:9042"
    deploy:
      resources:
        limits:
          memory: 16G

  # Creates keyspaces and tables
  init:
    image: cassandra
    container_name: init
    entrypoint: [ "/init.sh" ]
    volumes:
      - ./cql/init.sh:/init.sh

  # Runs YCSB for benchmarking
  ycsb:
    image: ycsb
    container_name: ycsb
    build: 
      context: .
      dockerfile: Dockerfile.ycsb
    volumes:
      - ./output/ycsb:/usr/src/ycsb/output/ycsb

