version: '3.8'
services:
  # Creates the cassandra node
  cassandra:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        CONFIG_PATH: ${CONFIG_PATH}
        CQL_PATH: ${CQL_PATH}
    ports:
      - "9042:9042"
    image: cassandra
    container_name: cassandra
    deploy:
      resources:
        limits:
          memory: 16G

  # Creates keyspaces and tables
  init:
    image: cassandra
    container_name: init
    entrypoint: [ "/init.sh" ]
    volumes:
      - ./cql/init.sh:/init.sh
